"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# BUILD PATHS INSIDE THE PROJECT LIKE THIS: BASE_DIR / 'SUBDIR'.
BASE_DIR = Path(__file__).resolve().parent.parent


# QUICK-START DEVELOPMENT SETTINGS - UNSUITABLE FOR PRODUCTION
# SEE HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/HOWTO/DEPLOYMENT/CHECKLIST/

# SECURITY WARNING: KEEP THE SECRET KEY USED IN PRODUCTION SECRET!
# LOAD THE SECRET KEY FROM THE .ENV FILE FOR SECURITY
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: DON'T RUN WITH DEBUG TURNED ON IN PRODUCTION!
# LOAD DEBUG MODE FROM .ENV FILE. IT'S SAFER TO DEFAULT TO FALSE.
DEBUG = config('DEBUG', default=False, cast=bool)

# LOAD ALLOWED HOSTS FROM .ENV FILE.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')


# APPLICATION DEFINITION

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 3RD PARTY APPS
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'guardian',
    'safedelete',
    'django_celery_beat',
    'django_prometheus',

    # LOCAL APPS
    'users.apps.UsersConfig',
    # 'PAYMENTS.APPS.PAYMENTSCONFIG',
    # 'CONTENT.APPS.CONTENTCONFIG',
    # 'TICKETS.APPS.TICKETSCONFIG',
]

MIDDLEWARE = [
    # PROMETHEUS METRICS MIDDLEWARE SHOULD BE FIRST
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS MIDDLEWARE
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # PROMETHEUS METRICS MIDDLEWARE SHOULD BE LAST
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# DATABASE
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#DATABASES
# CONFIGURED TO USE POSTGRESQL WITH SETTINGS FROM THE .ENV FILE.
# THE ENGINE IS WRAPPED BY DJANGO-PROMETHEUS TO EXPORT DATABASE METRICS.
DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
    }
}

# TELL DJANGO TO USE OUR CUSTOM USER MODEL
AUTH_USER_MODEL = 'users.User'

# AUTHENTICATION BACKENDS (FOR DJANGO-GUARDIAN)
# HTTPS://DJANGO-GUARDIAN.READTHEDOCS.IO/EN/STABLE/CONFIGURATION.HTML
# THIS IS REQUIRED FOR OBJECT-LEVEL PERMISSIONS.
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # DEFAULT
    'guardian.backends.ObjectPermissionBackend',
)


# PASSWORD VALIDATION
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#AUTH-PASSWORD-VALIDATORS

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# INTERNATIONALIZATION
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/TOPICS/I18N/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# STATIC FILES (CSS, JAVASCRIPT, IMAGES)
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/HOWTO/STATIC-FILES/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA FILES (USER UPLOADS)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# DEFAULT PRIMARY KEY FIELD TYPE
# HTTPS://DOCS.DJANGOPROJECT.COM/EN/4.2/REF/SETTINGS/#DEFAULT-AUTO-FIELD

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DJANGO REST FRAMEWORK SETTINGS
# HTTPS://WWW.DJANGO-REST-FRAMEWORK.ORG/API-GUIDE/SETTINGS/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
}

# DRF SPECTACULAR (API DOCS) SETTINGS
# HTTPS://DRF-SPECTACULAR.READTHEDOCS.IO/EN/LATEST/SETTINGS.HTML
SPECTACULAR_SETTINGS = {
    'TITLE': 'Government Services Portal API',
    'DESCRIPTION': 'API documentation for the Government Services Portal backend.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# SIMPLE JWT SETTINGS
# HTTPS://DJANGO-REST-FRAMEWORK-SIMPLEJWT.READTHEDOCS.IO/EN/LATEST/SETTINGS.HTML
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# CORS SETTINGS
# HTTPS://GITHUB.COM/ADAMCHAINZ/DJANGO-CORS-HEADERS
# ADD YOUR FRONTEND URL HERE FOR DEVELOPMENT. FOR PRODUCTION, BE MORE RESTRICTIVE.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# YOU CAN ALSO USE CORS_ALLOW_ALL_ORIGINS = TRUE FOR INITIAL DEVELOPMENT, BUT IT'S INSECURE.

# CELERY CONFIGURATION
# HTTPS://DOCS.CELERYQ.DEV/EN/STABLE/DJANGO/FIRST-STEPS-WITH-DJANGO.HTML
CELERY_BROKER_URL = f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/0"
CELERY_RESULT_BACKEND = f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# DJANGO-SAFEDELETE CONFIGURATION
# HTTPS://GITHUB.COM/MAKINACORPUS/DJANGO-SAFEDELETE
# SETS THE DEFAULT DELETION POLICY TO SOFT-DELETE FOR ALL MODELS THAT INHERIT FROM SAFEDELETEMODEL.
SAFE_DELETE_POLICY = 'soft'
